### PR TITLE
Fix/uppy remove link

### LINKED ISSUE #295: Temporarily remove Google Drive & Uploading through Link on Uppy
Currently both of them are not working on Dega Studio. Let's remove this until the issue is resolved.

We need to add these back after the following issue is fixed: https://github.com/factly/dega-studio/issues/144

### PR DESCRIPTION
**Pull request by Bhumi101097**
Temporary removed option to upload image through google drive and url

Closes #295

### CODE REVIEW

**Comment by shreeharsha-factly** [comment]
Instead of removing those plugins can you downgrade Uppy versions according to Mande studio.

**Comment by deshetti** [comment]
@Bhumi101097 @shreeharsha-factly If this is just not working locally and is working as expected in the cloud-hosted instance, we should try to fix it locally rather than disabling it.

From our discussion, the link is working as expected in cloud-hosted instance. How about from Google Drive?

**Comment by fyrepenguin** [comment]
Uploading through Google drive is working on the cloud-hosted instance as well but not working locally

**Comment by deshetti** [comment]
Closing this PR as this is an issue just locally and the cloud instance works just fine.

**Pull request closed without merging**
